version: "3.8"
services:
  nginx:
    restart: always
    image: nginx:1.19.6-alpine
    ports:
      - "8888:8888"
    depends_on:
      - ipfs
    volumes:
      - ./templates:/etc/nginx/templates
      - ./cache:/data/nginx
    environment:
      - NGINX_PORT=8888
      - NGINX_IPFS=http://ipfs:8080
      - NGINX_SECRET=1234

  ipfs:
    restart: always
    image: ipfs/go-ipfs:latest
    volumes:
      - ./export:/export
      - ./ipfs:/data/ipfs

    environment:
      - IPFS_PROFILE=server

    ports:
      - "4001:4001"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"

    command: "daemon --migrate=true --writable"
